/*
 * College Football Data API
 * This is an API for accessing all sorts of college football data.  Please note that API keys should be supplied with \"Bearer \" prepended (e.g. \"Bearer your_key\"). API keys can be acquired from the CollegeFootballData.com website.
 *
 * OpenAPI spec version: 3.4.0
 * Contact: admin@collegefootballdata.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.21
 *
 * Do not edit the class manually.
 *
 */

import {ApiClient} from '../ApiClient';

/**
 * The Player model module.
 * @module model/Player
 * @version 3.4.0
 */
export class Player {
  /**
   * Constructs a new <code>Player</code>.
   * @alias module:model/Player
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>Player</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Player} obj Optional instance to populate.
   * @return {module:model/Player} The populated <code>Player</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Player();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('first_name'))
        obj.firstName = ApiClient.convertToType(data['first_name'], 'String');
      if (data.hasOwnProperty('last_name'))
        obj.lastName = ApiClient.convertToType(data['last_name'], 'String');
      if (data.hasOwnProperty('team'))
        obj.team = ApiClient.convertToType(data['team'], 'String');
      if (data.hasOwnProperty('height'))
        obj.height = ApiClient.convertToType(data['height'], 'Number');
      if (data.hasOwnProperty('weight'))
        obj.weight = ApiClient.convertToType(data['weight'], 'Number');
      if (data.hasOwnProperty('jersey'))
        obj.jersey = ApiClient.convertToType(data['jersey'], 'Number');
      if (data.hasOwnProperty('year'))
        obj.year = ApiClient.convertToType(data['year'], 'Number');
      if (data.hasOwnProperty('position'))
        obj.position = ApiClient.convertToType(data['position'], 'String');
      if (data.hasOwnProperty('home_city'))
        obj.homeCity = ApiClient.convertToType(data['home_city'], 'String');
      if (data.hasOwnProperty('home_state'))
        obj.homeState = ApiClient.convertToType(data['home_state'], 'String');
      if (data.hasOwnProperty('home_country'))
        obj.homeCountry = ApiClient.convertToType(data['home_country'], 'String');
      if (data.hasOwnProperty('home_latitude'))
        obj.homeLatitude = ApiClient.convertToType(data['home_latitude'], 'Number');
      if (data.hasOwnProperty('home_longitude'))
        obj.homeLongitude = ApiClient.convertToType(data['home_longitude'], 'Number');
      if (data.hasOwnProperty('home_county_fips'))
        obj.homeCountyFips = ApiClient.convertToType(data['home_county_fips'], 'String');
      if (data.hasOwnProperty('recruit_ids'))
        obj.recruitIds = ApiClient.convertToType(data['recruit_ids'], ['Number']);
    }
    return obj;
  }
}

/**
 * @member {Number} id
 */
Player.prototype.id = undefined;

/**
 * @member {String} firstName
 */
Player.prototype.firstName = undefined;

/**
 * @member {String} lastName
 */
Player.prototype.lastName = undefined;

/**
 * @member {String} team
 */
Player.prototype.team = undefined;

/**
 * @member {Number} height
 */
Player.prototype.height = undefined;

/**
 * @member {Number} weight
 */
Player.prototype.weight = undefined;

/**
 * @member {Number} jersey
 */
Player.prototype.jersey = undefined;

/**
 * @member {Number} year
 */
Player.prototype.year = undefined;

/**
 * @member {String} position
 */
Player.prototype.position = undefined;

/**
 * @member {String} homeCity
 */
Player.prototype.homeCity = undefined;

/**
 * @member {String} homeState
 */
Player.prototype.homeState = undefined;

/**
 * @member {String} homeCountry
 */
Player.prototype.homeCountry = undefined;

/**
 * @member {Number} homeLatitude
 */
Player.prototype.homeLatitude = undefined;

/**
 * @member {Number} homeLongitude
 */
Player.prototype.homeLongitude = undefined;

/**
 * @member {String} homeCountyFips
 */
Player.prototype.homeCountyFips = undefined;

/**
 * @member {Array.<Number>} recruitIds
 */
Player.prototype.recruitIds = undefined;


